### ISSUE TITLE
License choice discussion

### ISSUE THREAD

**Issue by YHuUBC** [UBC-MDS/easyphysics#85]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly dicussed.

**Comment by Mengjun74** [comment]
There are a lot of Licenses, which one is the best for our project? Any Ideas guys?

**Comment by YHuUBC** [comment]
We are currently using an MIT license, which allows users to reuse code for any purpose. Also, it provides no warranty at all (so, as developers, we do not have legal liabilities). The negative side is that we do not have the copyright of this package and its code in some sense; others have our automatic permission to use/reuse and further development. If we do not want to make any profit with this package (and do not mind if other people might want to gain profit using our package), I think it is okay to stay with the MIT license. Any other ideas?

**Comment by revathyponn** [comment]
I agree with the suggestion of @YHuUBC MIT license allows users to recode for any purpose. If we are looking for other options to solve copyright issues then we can consider the Apache License 2.0, It provides patent protection for the users. The Apache 2.0 is being used by many open source projects such as Apache Hadoop, Apache Cassandra providing access to support and collaboration.

**Comment by nik11susan** [comment]
Hi Team!
I found [this link](https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633) very helpful to understand howto pick a license. While I do believe MIT and Apache are great, I am a little favourable towards the GPL license. My thoughts are - our package is basically built to help people learn physics. In that case we should make it open source. I know it is a copyleft sort of a license and could be a very controversial opinion. What are your opinions on this?

**Comment by YHuUBC** [comment]
GPL sounds good too. Being opensource for educational purposes is good. Should we change the license to that?

**Comment by nik11susan** [comment]
@YHuUBC I was just reading up on the cons of GPL - and I think there are some drawbacks to using a GPL license. Because having a license that is strictly open source causes any other softwares that uses our package in a small portion of their code to become entirely open source. That is, if a developer is creating a package where 2% of it could be using our package - that would mean this developer has to make their entire project open source. This could potentially lead to people not using this package because of the license attached to it. Companies or programmers who would like to use our package to build other functionalities that could potentially help students, could end up not doing it. Would this actually stop them from finding another similar package (without GPL) to get their job done? Maybe. But I'm thinking we should think about this a little bit more. [This](https://softwareengineering.stackexchange.com/questions/7720/what-are-the-pros-and-cons-of-the-gpl) is a helpful link that describes the cons of the GPL license.

**Comment by YHuUBC** [comment]
That is a very good point. The link you shared shows MAC OS is not built on Linux because of the GPL license. It could cause trouble for our future users for being too strict on the open source requirement. Since our package is newly developed, how about we stick to MIT for now?

**Comment by nik11susan** [comment]
Exactly! I agree, we should probably keep the MIT license for now.
